cc_library(
    name = "dense",
    srcs = ["tt_dense.c"],
    deps = [
        "//code/math:matrix",
        "//code/math:math",
    ],
    hdrs = ["tt_dense.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
)
