cc_library(
    name = "types",
    hdrs = ["tt_types.h"],
    srcs = ["tt_types.c"],
    deps = ["//scale:scale"],
    implementation_deps = ["//debug:debug"],
    includes = ["."],
    visibility = ["//visibility:public"],
)
