cc_library(
    name = "math",
    hdrs = ["tt_math.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "matrix",
    srcs = ["matrix.c"],
    hdrs = ["matrix.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
)
